### ISSUE TITLE
Add a fake home screen

### ISSUE THREAD

**Issue by upintheairsheep** [lvcabral/brs-emu-app#120]
It would be nice for a fake home screen for use on a real TV that is connected to a PC as an alternative to the Retroarch functionality, you just put a bunch of Roku app folders and ZIP files in a folder, pass a command line argument to launch the home screen, and enjoy. The screen should have a main home section for normal Roku apps, a Search option for searching the channels in your folder, a Streaming Channels option where you can download Roku apps that are open source and sample apps, a Settings section where you change emulator settings, like the RCP and stuff, and an Exit section that contains a single button to exit the program. You could do an alternative launcher as well like a simple 9x9 grid of icons with the Roku aesthetic, or even the old Roku layout with the single row of apps.

**Comment by lvcabral** [comment]
There is a ticket for that, is #54 thanks for the additional suggestions.

**Comment by upintheairsheep** [comment]
It would be the best opportunity to add themes support.
