### ISSUE TITLE
ifStringOps

### ISSUE THREAD

**Issue by Matt-Moores** [lvcabral/brs-emu-app#129]
Using a string with 'ifStringOps' functions reports an error in the console
example:
`text.ifstringops.len()
text.ifstringops.mid(i,1)`

I know that this can be omitted but I have some old utility functions that still have 'ifStringOps' included.

https://developer.roku.com/en-gb/docs/references/brightscript/interfaces/ifstringops.md

**Comment by lvcabral** [comment]
More generic issue created on the library project, closing this ticket as this repository is only for the desktop app.
Reference: https://github.com/lvcabral/brs-emu/issues/164
