### ISSUE TITLE
Issue:  setMessagePort is not a function

### ISSUE THREAD

**Issue by ShriprasadM** [lvcabral/brs-emu-app#137]
<img width="1111" alt="image" src="https://github.com/lvcabral/brs-emu/assets/9314645/712a064f-118f-4187-aee2-97f5c49c977f">

> setMessagePort is not a function.

I have used following example, but even facing same issues with other examples too.

https://github.com/googleads/googleads-ima-roku-dai/tree/main/podserving_example

**Comment by lvcabral** [comment]
Hi @ShriprasadM the BrightScript emulator is based on the `brs-emu` library, that still does not implement the Roku SceneGraph framework, see the [limitations doc](https://github.com/lvcabral/brs-emu/blob/master/docs/limitations.md).
Currently it focus on the Draw 2D API that allows to create games and apps (not streaming).
We plan to support RSG in the future.

**Comment by lvcabral** [comment]
You will find links for 3 games with source code in the release page, so you can test the emulator: https://github.com/lvcabral/brs-emu-app/releases/tag/v0.10.31

**Comment by ShriprasadM** [comment]
Thank you @lvcabral  for an update
