### ISSUE TITLE
Toggle device toolbar buggy on Windows desktop

### ISSUE THREAD

**Issue by Komagb** [lvcabral/brs-emu-app#19]
When I have the Developer Tools open (docked on right side) and click on Toggle device toolbar, I can't click on anything on the top bar on the left side (such as Responsive, Online, or any of the numbers). But then if I switch the Dock side to the left, I CAN select those things on the top right (and have difficultly selecting the top menu items on the left side now!).

**Comment by lvcabral** [comment]
This same issue happens in Visual Studio Code, let's see if someone there fixes it :)

**Comment by lvcabral** [comment]
This was fixed in newer Electron versions, will be available in next release (v0.10.x)
