### ISSUE TITLE
Add support for Brightscript "dim" keyword

### ISSUE THREAD

**Issue by benjohnemmett** [lvcabral/brs-emu-app#62]
Brightscript allows using the "dim" keyword to create roArray objects. It is especially useful for creating multidimensional arrays. It appears that this is currently not supported by the emulator. 

https://developer.roku.com/docs/references/brightscript/components/roarray.md

**Comment by lvcabral** [comment]
I already have this issue opened in the interpreter project, will merge here when the feature is implemented there.

**Comment by benjohnemmett** [comment]
Gotcha, I'll go ahead and close this then.
